<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class DistroGroup extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('tbl_distgroups', function(Blueprint $table)
		{
			$table->string('DistGroupID')->primary();
            $table->string('DistGroupEmail')->unique(); // autogenerated. DistGroupID@email.com
            $table->string('Description');
            $table->string('OwnerID', 11);

            $table->foreign('OwnerID')
                ->references('UserID')
                ->on('tbl_users')
                ->onDelete('cascade');
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('tbl_distgroups');
	}

}
